### PR TITLE
Simplify how obs and var names handled in ZarrAnnData

### PR DESCRIPTION
**Pull request by Artur-man**
This PR is similar to the one in https://github.com/scverse/anndataR/pull/171 and includes other changes in scverse/anndataR@main too. 

Some tests are currently still failing but starting this PR to check em out! @keller-mark also feel free to review! 

**UPDATE**: We commited some test and _index fixes.

### CODE REVIEW

**Comment by Artur-man** [comment]
I see that most of your tests are using `MemoryStore` for writing and reading arrays. This is a bit different than the entire HDF5 backend of anndataR where temporary `h5ad` files are written for testing. 

https://github.com/keller-mark/anndataR/blob/87907159024d7c3152aedadb4a0196e373c6227a/tests/testthat/test-Zarr-write.R#L5-L14

Should all zarr write/read helper functions designed to accept both zarr paths as characters and `MemoryStore`s ?

**Comment by Artur-man** [comment]
I think I understand why you commented out this test, since read_*_mapping returns lists in different orders right :D 

https://github.com/keller-mark/anndataR/blob/87907159024d7c3152aedadb4a0196e373c6227a/tests/testthat/test-h5ad-zarr.R#L98-L103

**Comment by Artur-man** [comment]
I would say one way to go around this problem is the define additional name indexing for zarr stores, to capture the initial ordering of groups/arrays within h5?

**Comment by Artur-man** [comment]
I fixed a lot of tests and indexing bugs, all tests are now working and I have even replaced `example.zarr` with one that works great ... @keller-mark I would also love your input!

**Comment by keller-mark** [comment]
Thank you very much for the improvements/ bug fixes and getting it up to date with the original repo. All of the changes look good to me and the tests are passing locally, I will merge this and then open a PR into the original scverse repo.

**Pull request merged**
